### ISSUE TITLE
Why this version?

### ISSUE THREAD

**Issue by bispojr** [cloudhead/node-static#236]
Hi, 

Why does the more updated release has a lesser number than the previous one?

Best,

**Comment by brettz9** [comment]
Per https://www.npmjs.com/package/node-static , the last version published was 0.7.11 . That is also the version in `master`. The prior version was 0.7.10.

I am guessing you might have run into my fork at https://www.npmjs.com/package/@brettz9/node-static which has a lower version because it was a separate package, thus not bound to follow this package's versioning.

I created that fork mainly to resolve some vulnerabilities and because this project's author had not been responsive at the time, but subsequently invited me to take over the work with this project. However, as per #231 , we are still waiting on the author setting up npm releases for this project, so this project is still at 0.7.11.

Does that answer your question?

**Comment by bispojr** [comment]
Yeah, @brettz9 !

Thanks for the detailed response.

Best
